### ISSUE TITLE
Bbr support

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/postgres-release#26]
As an operator I would like to be able to use [bbr](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore) to backup and restore my postgresql databases.

**Comment by valeriap** [comment]
Hi @rkoster,
may you clarify your scenario?
Do you want to enable B&R inside a CF deployment or are you using a stand-alone postgres release?

The BBR has developed an [SDK](https://github.com/cloudfoundry-incubator/backup-and-restore-sdk-release) that can be leveraged for integrating with BBR and that also includes jobs for backing up and restoring a Postgres database.
The integration so far has occurred at client level since in this way the client can coordinate the backup if more stores are used (like db and object store for the cloud controller).

We have not tried it, but reading the docs we do expect it to work. We don't have a specific story for BBR in our backlog, but we would certainly evaluate PRs in case you find issues.

**Comment by rkoster** [comment]
My usecase is making a backup of the concourse database, which uses postgres-release. Concourse does not yet have support for bbr, and in the case of concourse I'm wondering if it would not make more sense to have bbr support at the database level. Since there are no pre/post backup hooks needed, just a db dump [is enough](https://docs.pivotal.io/p-concourse/backing-up.html) to restore concourse.

**Comment by valeriap** [comment]
@rkoster 
With [v29](https://github.com/cloudfoundry/postgres-release/releases/tag/v29) we delivered the first story around backup and restore. We have other two stories in the backlog to further improve it but this first stage should address your issue.

**Comment by rkoster** [comment]
@valeriap Thanks! already added bbr support to concourse, but will look at switching to this instead in the future.
