### ISSUE TITLE
[question] are multiple instances supported?

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/postgres-release#34]
Hello,
is it possible to configure multiple instances? For example:
```
jobs:
 name: pg1 => properties.databases: a, b
 name: pg2 => properties.databases: c, d
```

**Comment by valeriap** [comment]
@paolostivanin 
If I have properly understood, you would have more PostgreSQL instances on the same vm running on different ports.
The scenario is not possible because you cannot configure a postgres job to spawn multiple PostgreSQL instances and you cannot specify the same job twice in a instance group.

**Comment by paolostivanin** [comment]
ok, thanks!
