### ISSUE TITLE
Prometheus upgrade from 23.3.0 to 26.2.0 - DB Start Failed

### ISSUE THREAD

**Issue by Muruganfly03** [cloudfoundry/postgres-release#56]
Hi Team

We try to upgrade from 23.3.0 to 26.2.0 and during upgrade we failed with upgrade.

Task 605996 | 06:44:14 | Updating instance database: database/53a1cdb3-5aa9-47b9-91c3-2acb065d5c26 (0) (canary) (00:04:38)
                      L Error: Action Failed get_task: Task 923b6aa6-84dc-4f78-6658-84fe3841d7da result: 1 of 2 pre-start scripts failed. Failed Jobs: postgres. Successful Jobs: bosh-dns.

DB logs:
database/53a1cdb3-5aa9-47b9-91c3-2acb065d5c26:/var/vcap/jobs/postgres/bin#
[2020-02-21 06:44:14+0000] 3898     /var/vcap/packages/postgres-11.6/bin/pg_ctl -D 
/var/vcap/store/postgres/postgres-11.6 -l logfile start
[2020-02-21 06:44:14+0000] 3898
[2020-02-21 06:44:14+0000] 3898 /var/vcap/store/postgres/pg_upgrade_tmp ~
[2020-02-21 06:44:14+0000] 3898 Running in verbose mode
[2020-02-21 06:44:14+0000] 3898
[2020-02-21 06:44:14+0000] 3898 check for "/var/vcap/packages/postgres-9.6.8/bin" failed: No such file or directory
[2020-02-21 06:44:14+0000] 3898
[2020-02-21 06:44:14+0000] 3898 Failure, exiting

Existing files inside the directory:
database/53a1cdb3-5aa9-47b9-91c3-2acb065d5c26:/var/vcap/packages# ls -lrt
total 28
lrwxrwxrwx 1 root root 80 Feb 21 06:44 postgres-common -> /var/vcap/data/packages/postgres-common/48f53292835d7ef420d4c6b5d22abbdba7b5e04e
lrwxrwxrwx 1 root root 82 Feb 21 06:44 postgres_exporter -> /var/vcap/data/packages/postgres_exporter/89784b5241e6d926fdadf182be9cb8ecda34e47e
lrwxrwxrwx 1 root root 75 Feb 21 06:44 filesnitch -> /var/vcap/data/packages/filesnitch/a7787657f5f2fb52ee8320e450f5f8ef587fc134
lrwxrwxrwx 1 root root 73 Feb 21 06:44 bosh-dns -> /var/vcap/data/packages/bosh-dns/28a34d61581ca20880c7e5dbad623541fe6bd142
lrwxrwxrwx 1 root root 78 Feb 21 06:44 postgres-11.6 -> /var/vcap/data/packages/postgres-11.6/a7c6794a8f9dc2dc4ee66fa4e43962f85f2f6f36
lrwxrwxrwx 1 root root 74 Feb 21 06:44 fim_utils -> /var/vcap/data/packages/fim_utils/87595ea2ffd48a8dd439758dccd5f46e977a3f0e
lrwxrwxrwx 1 root root 80 Feb 21 06:44 postgres-9.6.10 -> /var/vcap/data/packages/postgres-9.6.10/448f10d2c6429ef66b3888209903c6f5b5

Kindly let us know what causing the upgrade to search old version directory.

**Comment by valeriap** [comment]
@Muruganfly03 from which version of postgres-release are you migrating? The landing release should be the v40 that bumps PostgreSQL 11.6.

**Comment by Muruganfly03** [comment]
@valeriap : I am migrating postgres from v28 to v40.

**Comment by valeriap** [comment]
@Muruganfly03 the major upgrade requires both the old and the new bin directory [see code](https://github.com/cloudfoundry/postgres-release/blob/v40/jobs/postgres/templates/utils.sh.erb#L86-L90). The v40 release only includes `postgres-9.6.10` and `postgres-11.x` packages. Version `9.6.10` was introduced in postgres-release `v30`. A way to overcome this issue is to migrate first to the v30 and then to the v40.

**Comment by valeriap** [comment]
@Muruganfly03 Also please note that after a failed upgrade there are some [manual actions](https://github.com/cloudfoundry/postgres-release/blob/master/README.md#upgrading) to run before attempting again the upgrade.

**Comment by Muruganfly03** [comment]
We can use Prometheus bosh release -26.2.0 with postgres 30 upgrade? Is this one work? Then we can upgrade to version40?

**Comment by valeriap** [comment]
@Muruganfly03 As far as concern the postgres-release, per our [Upgrade Test Policy](https://github.com/cloudfoundry/postgres-release#upgrade-test-policy) we only test the upgrade from the latest postgres-release that bumps the previous PostgreSQL version; anyway I've reviewed the changes since v30 and there is nothing that may impact the upgrade. So migrating firstly to v30 and then to v40 looks as a good path.

**Comment by Muruganfly03** [comment]
Thanks @valeriap. Upgraded successfully to v30 and then to v40.

**Comment by valeriap** [comment]
Great!
